language: node_js
node_js:
- '0.12'
addons:
  sauce_connect: true
env:
  global:
  - secure: RadkZutt4zFQJDjfFDAXwKHE4jeNKgFlHnPOOzKz+L8GeDzwnucd41ZUJkwst8W9F0PwvyRmsf3QJiSZkdIPRWeWiBZwi8BuT4e/hOtHZXnURXc7O/SZXqUNZDdF/BLLqjIbS3A1gwUozaMkuBydGFIh5R25OUNd5A0M1r3yaOgyAukpRMdylG+iWkUFX6IhJCjzGtGmiXzm23TCIHxP/Qbvas292VFqEoMbm1Vao0B0L5dmBa7KtgxQJboMrrvP4irfcefQ3YXgKB2eJEIX2R87Mj3x+XDnezBVF0T3HIj78DUV5XBzNARILNBLqgYEf2RB+L1K6Hz3m3yc2S+TNESVkqOT53HQo5PRbXT0TxTt+TNVuRDj3TunOB0T8GjqmRuqovHziC5AK8rphGrvJJj1zK1TwiGiPFc6BzuqMUGDeBXw1MSMtqC/WDtZOTOrMdvzv44SIYzTZ11oCZAp+gUtA27iImmP876UqpZuKDUht4ikoHQ4OeM3p22TJbP1v+wP7X6RTQ6HMVY6xK9pc/KSo+5s5gZUGxHO1/9l1XqK1jAZ1UmQdwF8W6bh2FyrM3TCSw4zxLp8dFoMkzHvP2Q4Vdb7uHUY6ht0P5Exa5tF+L32orpIJf+OfA1GnfkebfBTLdHoEusjDlsdD+u4qCQbGdMDlLNUwTVhnWB+KKM=
  - secure: mVJlCGoBQ5D8q8V7bKCelX0/WxkzrK1ZaJ5L4414lA9Z7UYfsgx/QBW9HkmJkTjDsExB4eHc8iu6vxOyTJc/pAOBS2Y+RKNYmUt/4j5976jkRX8iewCjIEKpXxD8x7qAGUaDlCd2cpq8ROGhdzcNLhDMnQCj3zCbBOiT/CVYfLbv1SCeBs5NIiWFaGTiwbLOYiPffJFFaQHr4O1GQ5oi+giRg2JODnHVtfXML39mgIBgJp0bqSZoOpC8TH2SvZrze4n5oDnAyIMZBQPtVIZrOsqmZwJFT7ULaakrHSFZIKnSs55uxopyzYzKzXAmBeV0DCwfCRQrAWUZmwjYl9Aw35lhgvZXEZpJBG9n0Wh3XbGgSdl/QxsDzP5sl/PXW23gbn1J1FS292UhrTT1ebU/XasWYyPsIMbSUb22EOkvdmvroaVUCGAtbgX4uEa+H3ls+cz3AxQoUDDL1G7vXFfyEocEJuxJKuwH12ssySzsmLT8K6QgKJHhkmrmqClfoUx9efZeJaHAA0n3kSIQrY0mGi9ZwkFDF1cpJyFSqJcloONF5lciAW1sEEN++8+r6N6RkZpfYGCHa0TaYeFWmqz0SWp3U18+ON06WibvsboVtg2ntXkhw36qZP7xxlsvT7D1T+QNBDGfm6v0pvZXw0Y1iw3Ky3PHHAzr/uzIKjMISjM=
before_script: ./node_modules/.bin/bower install
branches:
  except:
    - gh-pages
