language: node_js
node_js:
- '0.12'
addons:
  sauce_connect: true
env:
  global:
  - secure: ntJWaJOR2CBUKRNKpAS4hVOQT40QXcRx1DThmanvsrjFAOjNgapchPpkrHmxnz7ZzLppdwiWtsQw3RV6spEsRMXSqUcVeve6ngw32Ozk+xmP/xX/s9N3hVHq3iJr5biKzGK5RaXYdVM/RAXimHS7Q0SsmNXMJEeMpJtrIlUX6/CS0LVuVxF1hXnieGR564+ASIxPNu8RQZWa701YmfS6E2a0fC3hT+iM9LNabsoGEw1xk+b0d1vXjFTXxBGexfvuW9Ju6E/lhoSJgY5zJCp0Q2bAMoKjgq1AhUcgbI0X5YZ+5PJC9DIPIpPy0RvY2rQixnYC6dV4u718DCJIy2YCD/j70S9hnb6UUggeUAn+micoTskr6gbe0mxBrrEvO05bmqpyv05/ZEjHxE8tt8HDeySWJu1rt6Vkumr5eXF3sRNKGWio1pKr0li+SqLD53Wp6p6lFDya8WQuavsg8/c/z/RGUND87dpuJDgPPiQsMjckawLwBJ+EL8K9UBTGyG60FDTTqG8GUvFK4YlbAH67ks2LcyrW2k4eYE9FgGRhvCPiBfy2198efiGKmt9Kz1FKlsC0WxlfVUQZf0K9nCnEfWkmqhq36/TAAZ0b2Pdz5+U0cARdQucCm9qtRGrkszSFoMxMTTLn0UTaCelNJfsJH9NXOyC3OKu4B37HSeCVYKU=
  - secure: CU0m0Ajbbix20K3tm+sGn6/PS4nlf7kvXmaG9lC1+VbBgyiaKSpzrJgf3RzHGkaygnAwM3u9FYc4Fkc+8x3tQfeWrqClxzmAmDHSCOACdcYIvGW28Y8/waajVZNviKFxr7XTsIBKUi1oapZ6CS2ERz9cEhGDQBvuisea+5ocPWlCn0oHQdff/zM2kZI0eKaaXjzz/5QCtA7izxLHz7baLL3hG5cZTWqs6sqQtBYX2yPMIOYzZgveThlylSj2deCWKUPD2mzA9hU0VrDmC9gz3ABI6NhSLsuzVbULdm9DH908rNWo1qTHg31NpUMw8nKOQBPV/CfpM9FDQ/xShlDGJeUDITarhd8DOqDoTlsN6uEbWdXt/1/ka9UOuio8kyMNZLSveRpG8uIxuoZhm3NTnFVGPh+4Wc0GekYMQ/pGUXrNioonWJP10pyqMpY3lKfMC40EZDXtbX/cy6zkLEesGyR6IgzrDG8otrNPvLd6qXUTR8sP3okLR9yg6klRJ6+YFaTwTFUWoMg0BpmFa19XZfVVAEvhwkHBmI/iAwbEN5Q+BA/hXcyvLI3jYkY+aiC5TQ7IVa519Z5jisCi1XZPyrY9HHWknKppRyVg7fbhDTXh+dhmNpcQw3dSBBmvUUSF708zEqLxddE0VYQxOoZhmbSiCcqvIu27t38/MQRYHJA=
before_script: ./node_modules/.bin/bower install
branches:
  except:
  - gh-pages
