language: node_js
node_js:
  - "0.12"
addons:
  sauce_connect: true
env:
  global:
    - secure: POsOdATnuaudFC1Jx4fkVEbafHwtMBiOll7bHKDH1ZsHKyTMfk/dGGrLFibcdDP6t9r3xzz1pMrW/vhbNgfhBWEAvhKvZhZz2lDnxug1c/hbhPW1kLoHJ25kJp06zu1fYgYREJD3ggQZ8KDT5wJvVhdo7iyXvRJgaYWaSt9kWZcCEJ68nYZV2qygKgzKxVOTIj/Bj6xkqP1wV7TvPxRlu7UeyQtXIm0bUHXE7dm9bGnTNuJqYler+/3uD38nGruVqlxseXRJrLmzTJDMyvcygppigVtwMpMQSvVlnz2rNtBYtX2F1tdGn3xCVKndeqMBt+IwficFjHG7NtcpWse9f8KZT1R2HQwyF6TJVk50PEIZCntgrV4RP7U0h2H9CBnF0YSGqSQfw+7noFPY4OE/tvdoo9dmUyxWXyEY3ej1f/UpIlIqOvWqSVDBORPVFGsDaMqQ6299FpQag8M2qCnWesp3KjaYlJcJ0jIhQ+ZsQ35y/8Qy4KfDmbzVVDFlDOdqBEf7LXtAD3bsNoo5rNlP7thoV/tZjWH/aHLlKIuYOmf3E4C7tFQDoa1WsU3iGoTPfueYQlzNDFKZ334kBLGUOgyZgnzaeHEqIpOQwWP+/ObWe28X6uz+f0bO+OQDdXXRTMGmgtDqslsxSQ5F3O4M4O27STQNg+vK1Iy299nYhU8=
    - secure: gd+fz18vqQZe7CsmjyifjmNdazNJu4xYStvQyCDx7hWhiq7g++nwuOfSoOxisD1t7a8x/cvcgciDvtNbw+mIwvHyaHwSBmj1tDyI3lYbpHSGVscZOMCpecXlDF8CAQJHhNRvqLhyNX+cL6pDzZp4FJIRwMrxCibdC8le6Gsh6ergb6EMiJ9abOgAqFF7XTwmkqNlHY1+Aw1CLBXfePMoqiNjx86pv+kDgnSQxsl6xqBXOFc/XCvWT7fEgIG82iYahrwDsNA1hmaDW/t7Um9etbqKXaia4RVxm81j9AXwn5zSQjE8ibE3x/V6PFxyZnkUC6COLdmfh50TWm0vimsoDXfR/dQPK6+IDZLZ2joghogaDv5T/inBwTuRwr48/UElBJaoReg/bK4PSann6ghpdZN1tiyISO+H1zJuD4O+A+bAgJn2mSAPLd5VbegpnG/ciHrzsMz+7dh61/+2ck4VocFESTyQsf+7i+KCtpMWLyX3n0JL+NNIEhwjoUwvPl66GKcQsyGHkb7bvcCQ4RHOHD+p+7+2zIzFNHrH7a9IWOJBM0QcaLgVOYh1ZBdC8m5yB8MJkGqjZfKrJUMsiNrQo8x3jRLlojvAAkhrVnkE325sjXB0TUYeXlPa/BSQpU/1q2uoP/FYeqCTe06cY0RZMa3hvBDhjUcI/bA8h3QpQoY=
branches:
  except:
    - gh-pages


