language: node_js
node_js:
  - "0.12"
addons:
  sauce_connect: true
env:
  global:
    - secure: YEXLKYgwZ4H9HxzcK9mwI//AfnwvfLm5WIdlLrZg47zSVtnN4hNjPOzO2fV1seEVKD7BAHOsudZpb6jLkyY/rEoEQzC0BnU0zRyS+I5qvolJSuJhR4hzLfCeqfCE1VW8FyfePSdSCnJprmske5bMHfx5nvpR3MNVCRl9FlfW+ZtP+DVj763m2EqTupACbgjwzoDBozSpNDlPd2MTw9rXhRFovkkh7YWb9dEIhPHqhfboYHQB61GLO0ac5L42mDLSSK9QRlbej9c9E56MogGuwwqebZyBDJ2rk+PmrU4GDdHse6mxl0vE0BiQo8OWvkoRv9BZDof2z4MigX2SJ08h33eycuayHc4csYAJmimPfaITKg0WtB23dTwTa5tKANXTVJlmz46brNurM2lIJKMggmyOK+MHXZiMvk5xjYUOkXKik+gPYO+jTVkU7/kfNE9i+JILEw/uZ8vzWfm612BYxRwqj/o1ajKNvb7ET49NXVn8OljdyXFJZDCadHgVEo+9XP3b8z8gvh99p1YtAE4IaVcUu3BYCAW4yRJ2T7WstdY9uBNWqIcC80vCXaRS2LSRHRrT3m1eB3J2Deg9G3Wzq5mkzjoXkRHg5lcxyPrTa0u/UiOxM6Lugw6UYPfD6gH4oHkoXQnvSN/rICBZ4RM1qYV/CaLOxmhcjLlPAG1x8VU=
    - secure: GXaulLBgFSM2ZiMk3vMu3SHewbJKaf1884/5Goll8JvwCt3vEYT6NzmSj7R3kS1AuWTblGN3oSANyIKKG242YEgbXwS3FS/0aIH2qjfatE8d+Owso+O4WnqBOKOu+F0vrf9gXv2bAbS3ECOI3vAiQZ6KRu3RJvWubg1hzmhKAV62zZDTR/fdVKDJvOKlAG8ujycE25z8UenM7qrNKu0enmultFwlZfwsdkmPvx/N9Vt6W0IS33mvqh3uO6tUK3Svnbds1nrsYzxyZHzqCGI94loke8gXEVV5YcTK1SCjyQ75NKj2L7cc3zD4/n4nFvJbMescczaEfIYjf2pSTZknTAruySWMe7V+6OCdMMhTvkqxzo5iq8C0V7ZCVnw8/pWHbkr4HlFzRX2VhfjRlzc22dxXMlHbljfqw0drsDXQiSAnJ83H1MHtyvcwmmaSGD1lyJ/FerHausMEuIiP6sti29C13OFOKieIP/RjYRBdRTwRL/tLJ/puTkr5mvhAhcyfEbE4q+/QWBA61e+U8pZN1qK6IhTBIryUUWySao8F6jiIW/QgWOrTn2fGRc0PTItMJ/VL+Bdi92DLiSEFc+z/Wj+2z3WV7Ea+6UgqqlTO3kMBCiG5Cu9Ib1XGE36tzDSvWlgMCp9RjeUEKzFgt3Ju1uLkZ502oc99VaP8TzaePtU=
script: npm test
branches:
  except:
    - gh-pages
